[package]
name = "near-enhanced-api"
version = "0.0.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
publish = false
# Please update rust-toolchain.toml as well when changing version here:
rust-version = "1.58.0"
edition = "2021"

[dependencies]
derive_more = "0.99.9"
dotenv = "0.15.0"
hex = "0.4"
strum = { version = "0.24", features = ["derive"] }

awc = "3.0.0"
actix = "0.13.0"
actix-web = "4.0.1"
actix-http = "3.0.4"
actix-cors = "0.6.1"
futures = "0.3.5"

tokio = { version = "1.1", features = ["full"] }
tracing = "0.1.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5.13", features = ["runtime-tokio-native-tls", "postgres", "bigdecimal", "json"] }
validator = "0.12"

paperclip = { version = "0.7.0", features = ["actix4"] }

near-primitives = "0.14.0"
